// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package queries

type Account struct {
	ID           int32
	Username     string
	PasswordHash string
	Salt         string
}

type Equipment struct {
	ID         int32
	Body       int32
	Legs       int32
	Helm       int32
	MainWeapon int32
}

type Player struct {
	ID           int32
	AccountID    int32
	Name         string
	Class        int32
	StatsID      int32
	EquipmentID  int32
	Inventory    []int32
	CurrHealth   int32
	MaxHealth    int32
	CurrXp       int32
	PlayerLevel  int32
	RoomID       int32
	RecallRoomID int32
}

type Playerstat struct {
	ID  int32
	Str int32
	Con int32
}
